messages:
  progress: "&6%player% has completed a quest %current%/%cap% quests!"
  spawn: "&c%player% has spawned the pinata!"

settings:
  quests_cap: 2
  progress_complete_command: "pinataparty:pparty spawn ratskuii"
